name: Continuous Integration

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get -y install libgstreamer-plugins-bad1.0-dev
        cargo test --verbose
        cargo build --verbose
